version: '1.0'
services:
    app:
        build:
            args:
                user: laravel
                uid: 1000
            context: .
            dockerfile: ./.docker/Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        networks:
            - backend
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d/
        networks:
            - backend
    db:
        image: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        ports:
            - "9909:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - backend
volumes:
    db-data:
networks:
    backend:
        driver: bridge
